source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

pod 'MTGeometry'
# https://github.com/samgreen/CGVector-Awesome.git
#pod 'AFNetworking', '~> 2.4'
#pod 'WYPopoverController', '~> 0.3'
#pod 'MZFormSheetController', '~> 2.4'
#pod 'MMDrawerController', '~> 0.5'
#pod 'MagicalRecord', '~> 2.2'
#pod 'JSONModel', '~> 1.0'
#pod 'MBProgressHUD', '~> 0.9'
#pod 'DACircularProgress', '~> 2.2'
#pod 'SDWebImage', '~> 3.7'
#pod 'PureLayout', '~> 1.1'
#pod 'CocoaLumberjack', '2.0.0-rc'
#pod 'ChimpKit', '~> 3.1'
#pod 'SWTableViewCell', '~> 0.3'
#pod 'SSKeychain', '~> 1.2'
#pod 'BlocksKit' , '~> 2.2'
#pod 'AWPagedArray' , '~> 0.2'
#pod 'SSZipArchive' , '~> 0.3'
#pod 'JGActionSheet' , '~> 1.0'
#pod 'PayPal-iOS-SDK', '~> 2.7'
#pod 'EARestrictedScrollView', '~> 0.1.0'
#pod 'SMPageControl', '~> 1.2'
# pod 'WTReTextField', '~> 0.0.1'
# pod 'EAIntroView', '~> 2.7.0'
# pod 'MYBlurIntroductionView'